version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: npm-install-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: npm-install-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/cacache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm run test
          when: always

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Semantic Release
          command: npx semantic-release

workflows:
  version: 2

  test_and_tag:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - release:
          requires:
            - lint
            - test

  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
